main/akshyapower/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AkshyaPowerProvider


urlpatterns = default_urlpatterns(AkshyaPowerProvider)

main/urls.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed 
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes  
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, 
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE 
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.                
'''



from django.conf.urls import url
from .views import *
urlpatterns = [
 
    url(r'^$', dashboard, name='dashboard'),
    url(r'^client/dashboard', client_dashboard, name='client_dashboard'),
    url(r'^inbox/$', issue_tracker, name='issue_tracker'),
    url(r'^manager/dashboard', manager_dashboard, name='manager_dashboard'),
    url(r'^user/(?P<id>\d+)/$', user_profile, name='user_profile'),
    #url(r'^client/inbox', client_inbox, name='client_inbox'),
] 

omportal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^pm/', include('prevmain.urls')),
    url(r'^site/', include('energysite.urls')),
    url(r'^complaints/', include('issues.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^issues/comments/', include('django_comments.urls')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

energysite/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.conf import settings
from prevmain.models import *

class Tilt(models.Model):
	TYPES = (('fix','Fix'),
		 ('seasonal','Seasonal'),
		)
	type = models.CharField(choices=TYPES,max_length=50,help_text="Choose panel tilt type according to the site design")
	angle = models.FloatField(blank=True,null=True,help_text="Please enter this angle if type is fixed")
	winter_angle = models.FloatField(blank=True,null=True,help_text="Please enter winter angle if type is seasonal")
	summer_angle = models.FloatField(blank=True,null=True,help_text="Please enter summer angle if type is seasonal")
	site = models.OneToOneField(EnergySite,related_name="tilt_site")
class HTPanel(models.Model):
	name = models.CharField(max_length=50,help_text="Please enter name according to your company's nomanclature pattern")
	TYPES = (('incoming','Incoming'),
		 ('outgoing','Outgoing'),
		)
	type = models.CharField(choices=TYPES,max_length=50,help_text="Choose panel type")

	model_no = models.CharField(max_length=50,help_text="Please enter model no. of the panel",blank=True)
	make = models.CharField(max_length=50,blank=True,help_text="Please enter make")
	serial_no = models.CharField(max_length=50,blank=True,help_text="Please enter serial no.")
	capacity = models.FloatField(null=True,blank=True,verbose_name="Rating",help_text="Please enter capacity in KV")
	site = models.ForeignKey(EnergySite,related_name="htpanel_site")
	def __unicode__(self):
                return '%s' % (self.name)


class Transformer(models.Model):
	name = models.CharField(max_length=50,help_text="Please enter name according to your company's nomanclature pattern")
	TYPES = (('auxillary','Auxillary'),
		 ('power','Power'),
		)
	type = models.CharField(choices=TYPES,max_length=50,help_text="Choose transformer type")

	model_no = models.CharField(max_length=50,help_text="Please enter model no. of the panel",blank=True)
	make = models.CharField(max_length=50,blank=True,help_text="Please enter make")
	serial_no = models.CharField(max_length=50,blank=True,help_text="Please enter serial no.")
	capacity = models.FloatField(null=True,blank=True,verbose_name="Rating",help_text="Please enter capacity in KVA")
	site = models.ForeignKey(EnergySite,related_name="transformer_site")
	htpanel = models.ForeignKey(HTPanel,help_text="Choose the HT Panel this transformer is connected to",blank=True,null=True)
	def __unicode__(self):
                return '%s' % (self.name)
class Block(models.Model):
	site = models.ForeignKey(EnergySite,related_name="block_site")
	company = models.ForeignKey(Company,related_name="block_company")
	block = models.CharField(max_length=255)
	def __unicode__(self):
                return self.block



class Inverter(models.Model):
	name = models.CharField(max_length=50,help_text="Please enter name according to your company's nomanclature pattern")
	block = models.ForeignKey(Block,help_text="Choose inverter block")
	capacity_connected = models.FloatField(null=True,blank=True,verbose_name="Capacity",help_text="Please enter capacity connected in KW")
	model_no = models.CharField(max_length=50,help_text="Please enter model no. of the panel",blank=True)
	make = models.CharField(max_length=50,blank=True,help_text="Please enter make")
	serial_no = models.CharField(max_length=50,blank=True,help_text="Please enter serial no.")
	capacity = models.FloatField(null=True,blank=True,verbose_name="Rating",help_text="Please enter inverter rating in KW")
	site = models.ForeignKey(EnergySite)
	transformer = models.ForeignKey(Transformer,help_text="Choose the transformer this inverter is connected to",blank=True,null=True)
	def __unicode__(self):
                return '%s' % (self.name)

class ModuleType(models.Model):
	name = models.CharField(max_length=50,help_text="Please enter name according to your company's nomanclature pattern")
	capacity = models.FloatField(null=True,blank=True,verbose_name="Capacity",help_text="Please enter capacity connected in W")
	def __unicode__(self):
                return '%s Watt' % (self.capacity)

class ConnectedModule(models.Model):
	type = models.ForeignKey(ModuleType,help_text="Choose Module Type")
	inverter = models.ForeignKey(Inverter,help_text="Choose inverter")
	quantity = models.IntegerField(verbose_name="Total Quantity",help_text="Please enter no. of modules of this type connected")
	def __unicode__(self):
                return '%s' % (self.type.capacity)


class AJB(models.Model):
	name = models.CharField(max_length=50,help_text="Please enter name according to your company's nomanclature pattern")
	model_no = models.CharField(max_length=50,help_text="Please enter model no. of the panel",blank=True)
	make = models.CharField(max_length=50,blank=True,help_text="Please enter make")
	serial_no = models.CharField(max_length=50,blank=True,help_text="Please enter serial no.")
	capacity = models.FloatField(null=True,blank=True,help_text="Please enter capacity in KV",verbose_name="Rating")
	site = models.ForeignKey(EnergySite)
	inverter = models.ForeignKey(Inverter,help_text="Choose the inverter this AJB is connected to",blank=True,null=True)
	def __unicode__(self):
                return '%s' % (self.name)

main/akshyapower/models.py
# Create your models here.

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/forms.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
'''




from django.forms import ModelForm
from django import forms
from .models import *
from django.contrib.auth.models import User

class UserForm(ModelForm):
	class Meta:
		model = User
                fields = ('username','first_name','last_name',)

main/akshyapower/views.py
import requests

from allauth.socialaccount.providers.oauth2.views import (
    OAuth2Adapter,
    OAuth2CallbackView,
    OAuth2LoginView,
)

from .provider import AkshyaPowerProvider


class AkshyaPowerOAuth2Adapter(OAuth2Adapter):
    provider_id = AkshyaPowerProvider.id
    access_token_url = 'http://localhost:9000/o/token/'
    authorize_url = 'http://localhost:9000/o/authorize'
    profile_url = 'http://localhost:9000/api/user/view/1/'
    supports_state = False
    redirect_uri_protocol = 'http'

    def complete_login(self, request, app, token, **kwargs):
	print app
	print token
        response = requests.get(
            self.profile_url,
            params={'access_token': token})
	print response
        extra_data = response.json()
	print extra_data
        #if 'Profile' in extra_data:
        extra_data = {
		'user_id': "1",
		'name': "333",
		'email': "sss@ss.com"
        }
	
        return self.get_provider().sociallogin_from_response(
            request,extra_data)


oauth2_login = OAuth2LoginView.adapter_view(AkshyaPowerOAuth2Adapter)
oauth2_callback = OAuth2CallbackView.adapter_view(AkshyaPowerOAuth2Adapter)

templates/main/calendar.html
{%load staticfiles%}
<!DOCTYPE html>
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Calendar | Sangoma Bootstrap Admin Template</title>
		<meta name="description" content="">
		<meta name="author" content="Walking Pixels | www.walkingpixels.com">
		<meta name="robots" content="index, follow">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- jQuery FullCalendar Styles -->
		<link rel='stylesheet' type='text/css' href='{%static "css/plugins/fullcalendar/fullcalendar.css"%}'>

		<!-- Styles -->
		<link rel="stylesheet" href="{%static "css/sangoma-red.css"%}">

		<!-- JS Libs -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="{%static "js/libs/jquery.js"%}"></script>
		<script src="{%static "js/libs/modernizr.js"%}"></script>

		<!-- IE8 support of media queries and CSS 2/3 selectors -->
		<!--[if lt IE 9]>
			<script src="js/libs/respond.min.js"></script>
			<script src="js/libs/selectivizr.js"></script>
		<![endif]-->
		
		<script>
			$(document).ready(function(){
				
				// Tooltips
				$('[title]').tooltip();

				// Tabs
				$('.demoTabs a').click(function (e) {
					e.preventDefault();
					$(this).tab('show');
					$('.fullcalendar, .full-calendar-gcal').fullCalendar('render'); // Refresh jQuery FullCalendar for hidden tabs
				})
				
			});
		</script>
		
	</head>
	<body>
		
		<!-- Full height wrapper -->
		<div id="wrapper">

			<!-- Main page header -->
			<header id="header" class="container">

				<h1>
					<!-- Main page logo -->
					<a href="login.html">O&M Portal</a>
					
					<!-- Main page headline -->
					<span>Solar Operations Management </span>
				</h1>
				
				<!-- User profile -->
				<div class="user-profile">
					<figure>

						<!-- User profile avatar -->
						<img alt="John Pixel avatar" src="http://placekitten.com/60/60">

						<!-- User profile info -->
						<figcaption>
							<strong><a href="user-profile.html">John Pixel</a></strong>
							<ul>
								<li><a href="#" title="Message inbox">inbox</a></li>
								<li><a href="#" title="Account settings">settings</a></li>
								<li><a href="login.html" title="Logout">logout</a></li>
							</ul>
						</figcaption>
						<!-- /User profile info -->

					</figure>
				</div>
				<!-- /User profile -->

				<!-- Main navigation -->
				<nav class="main-navigation navbar navbar-default" role="navigation">

					<!-- Collapse navigation for mobile -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".main-navigation-collapse">
							<span class="elusive icon-calendar"></span> Calendar
						</button>
					</div>
					<!-- /Collapse navigation for mobile -->

					<!-- Navigation -->
					<div class="main-navigation-collapse collapse navbar-collapse">

						<!-- Navigation items -->
						<ul class="nav navbar-nav">

							<li>
								<a href="index.html"><span class="elusive icon-home"></span> Dashboard</a>
							</li>

							<!-- Dropdown navigation items -->
							<li class="dropdown active">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="elusive icon-asl"></span> Components <b class="caret"></b></a>
								<span class="badge">23</span>
								<ul class="dropdown-menu">
									<li><a href="tables.html"><span class="elusive icon-th-list"></span> Tables</a></li>
									<li><a href="forms.html"><span class="elusive icon-align-left"></span> Forms</a></li>
									<li class="active"><a href="calendar.html"><span class="elusive icon-calendar"></span> Calendar</a></li>
									<li><a href="charts.html"><span class="elusive icon-graph"></span> Charts</a></li>
									<li><a href="gallery.html"><span class="elusive icon-picture"></span> Gallery</a></li>
									<li><a href="file-explorer.html"><span class="elusive icon-inbox"></span> File explorer</a></li>
									<li class="divider"></li>
									<li><a href="ui-buttons.html"><span class="elusive icon-cogs"></span> UI &amp; Buttons</a></li>
									<li><a href="typo.html"><span class="elusive icon-font"></span> Typography</a><span class="badge">7</span></li>
									<li><a href="grid.html"><span class="elusive icon-th"></span> Grid</a></li>
									<li><a href="goodies.html"><span class="elusive icon-heart"></span> Goodies</a></li>
								</ul>
							</li>
							<!-- /Dropdown navigation items -->

							<!-- Dropdown navigation with multi-level dropdown -->
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="elusive icon-file"></span> Extra <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><a href="eshop.html"><span class="elusive icon-file"></span> Online store</a></li>
									<li><a href="add-item.html"><span class="elusive icon-file"></span> Add item / product</a></li>
									<li><a href="invoice.html"><span class="elusive icon-file"></span> Invoice</a></li>
									<li><a href="user-profile.html"><span class="elusive icon-file"></span> User profile</a></li>
									<li class="divider"></li>

									<!-- 2nd level dropdown -->
									<li class="dropdown-submenu">
										<a href="#">Login Pages</a>
										<ul class="dropdown-menu">
											<li role="presentation" class="dropdown-header">Login Pages</li>
											<li><a href="login.html"><span class="elusive icon-file"></span> Login page</a></li>
											<li><a href="lost-password.html"><span class="elusive icon-file"></span> Lost password</a></li>
										</ul>
									</li>
									<!-- /2nd level dropdown -->

									<li class="dropdown-submenu">
										<a href="#">Error Pages</a>
										<ul class="dropdown-menu">
											<li role="presentation" class="dropdown-header">Error Pages</li>
											<li><a href="401.html"><span class="elusive icon-file"></span> Error 401</a></li>
											<li><a href="403.html"><span class="elusive icon-file"></span> Error 403</a></li>
											<li><a href="404.html"><span class="elusive icon-file"></span> Error 404</a></li>
											<li><a href="500.html"><span class="elusive icon-file"></span> Error 500</a></li>
											<li><a href="503.html"><span class="elusive icon-file"></span> Error 503</a></li>
										</ul>
									</li>
								</ul>
							</li>
							<!-- /Dropdown navigation with multi-level dropdown -->

							<li>
								<a href="docs/index.html"><span class="elusive icon-info-sign"></span> Docs</a>
							</li>
						</ul>
						<!-- /Navigation items -->

						<!-- Navigation form -->
						<form class="navbar-form navbar-right" role="search">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Type here to search&hellip;">
							</div>
							<button type="submit" class="btn btn-default"><span class="elusive icon-search"></span></button>
						</form>
						<!-- /Navigation form -->

					</div>
					<!-- /Navigation -->

				</nav>
				<!-- /Main navigation -->

			</header>
			<!-- /Main page header -->

			<!-- Main page container -->
			<section class="container" role="main">

				<!-- Grid row -->
				<div class="row">
					{%block content%}	
				{%endblock%}	
				</div>
				<!-- /Grid row -->

			</section>
			<!-- /Main page container -->
			
		</div>
		<!-- /Full height wrapper -->

		<!-- Main page footer -->
		<footer id="footer">
			<div class="container">

				<!-- Footer info -->
				<p>Built with love on <a href="http://getbootstrap.com/">Twitter Bootstrap</a> by <a href="http://www.walkingpixels.com">Walking Pixels</a></p>

				<!-- Footer nav -->
				<ul>
					<li><a href="http://support.walkingpixels.com/">Support</a></li>
					<li><a href="http://getbootstrap.com/getting-started/">Documentation</a></li>
					<li><a href="http://parallaq.com/">API</a></li>
				</ul>
				<!-- /Footer nav -->

				<!-- Footer back to top -->
				<a href="#top" class="btn btn-back-to-top" title="Back to top"><span class="elusive icon-arrow-up"></span></a>

			</div>
		</footer>
		<!-- /Main page footer -->

		<!-- Bootstrap scripts -->
		<script src="{%static "js/bootstrap/bootstrap.min.js"%}"></script>

		<!-- jQuery FullCalendar -->
		<script src="{%static "js/plugins/fullcalendar/fullcalendar.min.js"%}"></script>
		{%block scripts%}
		{%endblock%}
	</body>
</html>

templates/main/form.html
{%load staticfiles%}
{%load bootstrap3%}
{%include 'main/partials/header3.html'%}
<section id="content" class="table-layout">
 
<div style="height: 795px;" class="tray tray-center">
 
<div class="col-lg-12 admin-grid">
<form id="contact" method="post" action="">{%csrf_token%}
<div class="panel-body bg-light p30">
<div class="row">
<div class="col-sm-7 pr30">
<h3> Create a new site here </h3>
{% if messages %}
<ul class="messages">
    {% for message in messages %}

<div class="alert alert-micro alert-border-left alert-{{message.tags}} alert-dismissable">
<button type="button" data-dismiss="alert" aria-hidden="true" class="close">×</button><i class="fa fa-check pr15"></i> {{message}}.
</div>


    {% endfor %}
</ul>
{% endif %}


    {% bootstrap_form form %}

<button type="submit" class="button btn-primary btn mr10 pull-right">Creat Site</button>
</form>

 
</div>
</div>
</section>
 

{%include 'main/partials/footer.html'%}

{%block scripts%}

{%endblock%}

templates/main/index2.html
{%load staticfiles%}

{%include 'main/partials/header.html'%}
<section id="content" class="table-layout">
 
<div style="height: 795px;" class="tray tray-center">
 
{%block content%}    
{%endblock%}
</div>

</div>


</section>

 

{%include 'main/partials/footer.html'%}

{%block scripts%}

{%endblock%}

{%block extracss%}
{%endblock%}

templates/main/messages.html
{%load staticfiles%}

{%load bootstrap3%}
{% load timestamp_to_time %}          
{%include 'main/partials/header.html'%}
<section id="content" class="table-layout">
 
<div style="height: 795px;" class="tray tray-center">
 
<h3>Alerts: Monitor</h3>

<div class="pagination pull-right">
    <span class="step-links">
        {% if alerts.has_previous %}
            <a class="btn btn-sm btn-default"  href="?page={{ alerts.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ alerts.number }} of {{ alerts.paginator.num_pages }}.
        </span>

        {% if alerts.has_next %}
            <a class="btn btn-sm btn-default" href="?page={{ alerts.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

<form method="post" action="">{%csrf_token%}
    {% bootstrap_form form %}

<button type="submit" class="button btn-primary btn mr10 pull-right">Search</button>
</form>



<table id="message-table" class="table tc-checkbox-1 admin-form theme-warning br-t">
<thead class="bg bg-info">
<tr>
<th class="text-center">Device</th>
<th class="text-center">Alert</th>
<th class="text-center">Start Time</th>
<th class="text-center">Status</th>
<th></th>
</tr>
</thead>
<tbody>

{%for alert in alerts%}
<tr class="message-unread">
<td>{{alert.device}}</td>
<td class="text-center" style="max-width:30%">
<a href="/messages?alert_id={{alert.id}}">{{alert.alerttype.alert_title}} <br> {{alert.alert}}</a></td>
<td class="text-center fw600">{{alert.start_time|timestamp_to_time:"date"}}</td>
<td class="text-center fw600">
<span class="{%if alert.status == "open"%}badge-danger badge {%else%} badge-info badge {%endif%}">

{{alert.status}}
</span>
</td>
<td class="text-center">
<div class="btn-group">
<a class="btn btn-sm btn-link" href="/messages?alert_id={{alert.id}}">View</a>
<a class="btn btn-sm btn-link" href="/messages/update/{{alert.id}}">Update</a>
</div>
</td>
</tr>

{%endfor%}
</tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if alerts.has_previous %}
            <a class="btn btn-sm btn-default"  href="?page={{ alerts.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ alerts.number }} of {{ alerts.paginator.num_pages }}.
        </span>

        {% if alerts.has_next %}
            <a class="btn btn-sm btn-default" href="?page={{ alerts.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>



{%include 'main/partials/footer.html'%}

templates/main/strings.html
{%load staticfiles%}
{%load bootstrap3%}
{% load pretty_name %}          
{%include 'main/partials/header.html'%}
<section id="content" class="table-layout">
 
<div style="height: 795px;" class="tray tray-center">

<div class="col-lg-12 admin-grid">

<div class="col-md-12">
<div class="col-md-2 col-md-push-4">
<form action="/combiner/" method="post" class="string-form form col-md-12 col-md-push-2">
{%csrf_token%}
    {% bootstrap_form form %}
</form>
</span>
<img src="{%static "solar-inv.png"%}" style="width:200px" alt="inverter">
</div>
</div>

{%for data in final%}
<div class="col-md-1" style="margin-bottom:40px;min-height:700px">
<span class="device-name">
{{data.device|pretty_name}}:
</span>
<img src="{%static "smb.png"%}" style="height:100px" alt="smb">
<br>
<span class="smb-current">{{data.current}} A</span>
<br>
{%for report in data.data%}
<br>
<div class="pulse {%if report.reports.0.value == "0" %} pulse-red {%endif%}"></div>
<a href="#" class="string-name" data-toggle="popover" data-trigger="focus" title="{{data.device|pretty_name}} - {{report.parameter|pretty_name|upper}}" data-content=" Current: {{report.reports.0.value}}">{{report.parameter|pretty_name|upper}}- {{report.reports.0.value}} A
</a>
<br>
{%endfor%}


</div>

{%endfor%}






</section>
 

{%include 'main/partials/footer.html'%}

{%block scripts%}
<script>



function doPoll(){
	$(".string-form").submit();
        setTimeout(doPoll,10000);
    
}



$(function(){
setTimeout(doPoll,10000);
$('#id_inverter').on('change', function() {
$(".string-form").submit();
});

$('a.string-name').on('click', function(e) {e.preventDefault(); return true;});

});
</script>
{%endblock%}