issues/urls.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed 
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes  
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, 
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE 
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.                
'''



from django.conf.urls import url
from .views import *
from .forms import *
urlpatterns = [
 
    url(r'^$', dashboard, name='dashboard'),
    url(r'^search/$', view_issues, name='view_issues'),
    url(r'^contact/$', CreateIssueWizard.as_view([NewIssueForm,NewIssueForm])),
    url(r'^create_issue/$', create_issue, name='create_issue'),
    url(r'^api/create_issue/$', create_issue_api, name='create_issue_api'),
    url(r'^api/update_issue/$', update_issue_api, name='update_issue_api'),
    url(r'^reports/$', reports, name='reports'),
    url(r'^issues/mark/$', mark_issues, name='mark_issues'),
    url(r'^update_issue/(?P<issue_id>\d+)/$', update_issue, name='update_issue'),
    url(r'^issue/(?P<issue_id>\d+)/$', view_issue, name='view_issue'),
    url(r'^create_action/(?P<issue_id>\d+)/$', create_action, name='create_action'),
    url(r'^resolve/(?P<issue_id>\d+)/$', create_resolution, name='create_resolution'),
    url(r'^issue/(?P<issue_id>\d+)/assign/$', assign_issue, name='assign_issue'),
    url(r'^issue/(?P<issue_id>\d+)/pm/$', issue_pm, name='issue_pm'),
    url(r'^issue/(?P<issue_id>\d+)/reopen/$', issue_reopen, name='issue_reopen'),
    url(r'^issue/(?P<issue_id>\d+)/approved/$', issue_approved, name='issue_approved'),
    url(r'^issue/(?P<issue_id>\d+)/set_target_date/$', set_target_date, name='set_target_date'),
    url(r'^issue/escalate/$', escalate, name='escalate'),
] 

main/urls.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed 
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes  
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, 
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE 
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.                
'''



from django.conf.urls import url
from .views import *
urlpatterns = [
 
    url(r'^$', dashboard, name='dashboard'),
    url(r'^client/dashboard', client_dashboard, name='client_dashboard'),
    url(r'^inbox/$', issue_tracker, name='issue_tracker'),
    url(r'^manager/dashboard', manager_dashboard, name='manager_dashboard'),
    url(r'^user/(?P<id>\d+)/$', user_profile, name='user_profile'),
    #url(r'^client/inbox', client_inbox, name='client_inbox'),
] 

omportal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^pm/', include('prevmain.urls')),
    url(r'^site/', include('energysite.urls')),
    url(r'^complaints/', include('issues.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^issues/comments/', include('django_comments.urls')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issues/models.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed 
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes  
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, 
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE 
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.                
'''



from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from prevmain.models import EnergySite,Company,PMAlert
from smart_selects.db_fields import ChainedForeignKey 
from stock.models import PO

class Outage(models.Model):
	title = models.CharField(max_length=120)
	def __unicode__(self):
                return '%s' % (self.title)


class Description(models.Model):
	outage = models.ForeignKey(Outage)
	title = models.CharField(max_length=100)
	def __unicode__(self):
                return '%s' % (self.title)



class SubDescription(models.Model):
	description = models.ForeignKey(Description)
	title = models.CharField(max_length=100)
	def __unicode__(self):
                return '%s' % (self.title)



class Priority(models.Model):
	title = models.CharField(max_length=100)
	def __unicode__(self):
                return '%s' % (self.title)
class Status(models.Model):
	title = models.CharField(max_length=100)
	def __unicode__(self):
                return '%s' % (self.title)

class Device(models.Model):
    name = models.CharField(max_length=100)

    DEV_TYPES = (('meter', 'meter'),
                 ('htpanel', 'htpanel'),
                 ('control_room', 'control_room'),
                 ('transformer', 'transformer'),
                 ('field', 'field'),
                 ('sub_station', 'sub_station'),
                 ('ajb', 'ajb'),
                 ('transmisson_line', 'transmission_line'),
                 ('inverter', 'inverter'),
                 ('env_kit', 'env_kit'))

    device_type = models.CharField(max_length=100, choices=DEV_TYPES)

    make = models.CharField(max_length=100)
    rating = models.FloatField()
    site = models.ForeignKey(EnergySite)

    def __unicode__(self):
            return '%s' % (self.name)
'''
class Issue(models.Model):
    user = models.ForeignKey(User)
    site = models.ForeignKey(EnergySite)
    date = models.DateTimeField()
    details = models.TextField()
    OPTIONS = (('pending','pending'),('approved','approved'),('rejected','rejected'))
    status = models.CharField(max_length=100,choices=OPTIONS)

'''


class Complaint(models.Model):
	date_of_complaint = models.DateTimeField(verbose_name="Date of Filing")
	outage_start = models.DateTimeField(verbose_name="Issue starting time")
	time_to_detect = models.FloatField()
	site =  models.ForeignKey(EnergySite,verbose_name="Select the site this issue belongs to")
	complaint_by = models.ForeignKey(User,related_name="complaint_by",verbose_name="Who raised the issue?",null=True,blank=True)
	outage_type = models.ForeignKey(Outage,verbose_name="Select a category for this issue")
        description = ChainedForeignKey(
        Description,
        chained_field="outage_type",
        chained_model_field="outage",
        show_all=False,
        auto_choose=True,
	blank=True,
	null=True,
        verbose_name = "Type"
        )

        sub_description = ChainedForeignKey(
        SubDescription,
        chained_field="description",
        chained_model_field="description",
        show_all=False,
        auto_choose=True,
	blank=True,
	null=True,
        verbose_name = "Select a sub reason"
        )
        device = ChainedForeignKey(Device,null=True,blank=True,chained_field="site",chained_model_field="site",verbose_name="Location")

	priority = models.ForeignKey(Priority,verbose_name="Please choose the issue priority ")
	comment = models.TextField(verbose_name="Details related to the issue")
	status = models.ForeignKey(Status,verbose_name="What's the current status of the issue?")
	company = models.ForeignKey(Company)
	assigned_to = models.ForeignKey(User,related_name="assigned_to",null=True,blank=True,verbose_name="Do you want to assign this to any user?")
	user = models.ForeignKey(User,related_name="created_user",null=True,blank=True)
	created = models.DateTimeField(auto_now_add=True)
	target_date = models.DateField(null=True,blank=True)
	closing_date = models.DateField(null=True,blank=True)
	outage_end = models.DateTimeField(null=True,blank=True)
        impact_on_gen = models.BooleanField(default=True,verbose_name="Issue impacting generation?")
	capacity_down = models.FloatField(null=True,blank=True,default=0.0)
        fault_code = models.CharField(max_length=100,null=True,blank=True)
        plant_pr = models.FloatField(null=True,blank=True,default=0.0) 
        device_pr = models.FloatField(null=True,blank=True,default=0.0)
        radiation = models.FloatField(null=True,blank=True,default=0.0)
	genloss = models.FloatField(null=True,blank=True,default=0.0)
	is_read = models.BooleanField(default=False)
	def __unicode__(self):
                return '%s' % (self.description)

	def total_time(self):
		try:
			return self.outage_end - self.outage_start
		except:
			return 0

class ComplaintPM(models.Model):
	complaint = models.ForeignKey(Complaint)
	pmalert = models.ForeignKey(PMAlert)
	status = models.ForeignKey(Status)

class ComplaintPO(models.Model):
	complaint = models.ForeignKey(Complaint)
	po = models.ForeignKey(PO)
	status = models.ForeignKey(Status)


class ResolutionType(models.Model):
	title = models.CharField(max_length=100)
	
	def __unicode__(self):
                return '%s' % (self.title)



class Escalate(models.Model):
        complaint  = models.OneToOneField(Complaint)
	created = models.DateTimeField(auto_now_add=True)

class Action(models.Model):
	action_taken = models.TextField() 
	work_status = models.CharField(max_length=100) 
	complaint = models.ForeignKey(Complaint)
	created = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User)
	def __unicode__(self):
                return '%s' % (self.action_taken)



class Remark(models.Model):
	text = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	complaint = models.ForeignKey(Complaint)
	user = models.ForeignKey(User)
	def __unicode__(self):
                return '%s' % (self.text)



class ComplaintLog(models.Model):
	complaint = models.ForeignKey(Complaint)
	log = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	def __unicode__(self):
                return '%s' % (self.log)

class ComplaintResolution(models.Model):
	resolution = models.ForeignKey(ResolutionType)
	details = models.TextField()
	complaint = models.ForeignKey(Complaint)
	created = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User)
	outage_end = models.DateTimeField(null=True,blank=True,help_text= "Time of Ticket Closing")
	generation_loss = models.FloatField(help_text="Calculated Generation Loss in KWh")
	def __unicode__(self):
                return '%s' % (self.details)

issues/templates/issues/alerts_tabs.html
                          <table class="table bg-gray">
                  <tr class="bg-red">
                    <td>Status</td>
                    <td>Issue No.</td>
                    <td>Site</td>
                    <td>Date of Issue</td>
                    <td>Outage Start</td>
                    <td>Time To Detect</td>
                    <td>Outage Type</td>
                    <td>Description</td>
                    <td>Sub Description</td>

                  </tr>

{%for pm in today%}
                  <tr class="bg-gray">
	
			  <td>{%if pm.status.title == "open"%}<a href="/complaints/issue/{{pm.id}}/">{{pm.status}}</a>{%else%}<a href="/complaints/issue/{{pm.id}}/">{{pm.status}}</a>{%endif%}</td>
                    <td>{{pm.id}}</td>
                    <td>{{pm.site}}</td>
                    <td>{{pm.date_of_complaint}}</td>
                    <td>{{pm.outage_start}}</td>
                    <td>{{pm.time_to_detect}} days</td>
                    <td>{{pm.outage_type}} </td>
                    <td>{{pm.description}} </td>
                    <td>{{pm.sub_description}} </td>
                  </tr>

		  
{%empty%}
<tr>
<td colspan="14">
No issues found!
</td>
</tr>

                  {%endfor%}
<tr class="bg-red">
	<td>
	
		Total:</td>
	<td>{{totals.count}}
	</td>
	<td>
		Generation Loss:</td><td colspan="6"> {{totals.genloss}} KWh
	</td>

</tr>


	     		   </table>
                  

issues/templates/issues/analysis-ajax.html
{%if type == "simulated"%}

{%include "energysite/simulated.html"%}

{%elif type == "pm"%}

{%include "energysite/pmanalysis.html"%}


{%elif type == "reminders"%}

{%include "reminders/analysis.html"%}

{%else%}

{%include "energysite/analysis-rest.html"%}


{%endif%}

issues/templates/issues/assign_issue.html
{% load bootstrap3 %}
{% load staticfiles %}


        <form enctype="multipart/form-data" action="/complaints/issue/{{issue.id}}/assign/" method="post" role="form" class="col-md-12">
{% csrf_token %}

              {% bootstrap_form form %}


<input type="submit" class="btn btn-primary" value="Assign" />
</form>

issues/templates/issues/create_action.html
{%extends 'main/index.html'%}
{% load bootstrap3 %}
{% load staticfiles %}
{%block content%}

<!-- Content Wrapper. Contains page content -->
         <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Issue</li>
            <li class="active">Action</li>
          </ol>

        <!-- Main content -->
        <section class="content">
        <div class="row">
<div class="col-md-12"> 
           <h1>
           New Action
          </h1>
         
{% if messages %}
<div class="alert alert-success" role="alert">
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</div>
{% endif %}

<table class="table table-bordered table-stripped">
<tr>
<td><b>Issue No.</b></td>
<td><a href="/complaints/issue/{{complaint.id}}">{{complaint.id}}</a></td>
</tr>
<tr>
<td><b>Site</b></td>
<td>{{complaint.site}}</td>
</tr>
<tr>
<td><b>Description</b></td>
<td>{{complaint.description}}</td>
</tr>



</table>
 

        <form enctype="multipart/form-data" action="" method="post" role="form" class="col-md-12">
{% csrf_token %}

              {% bootstrap_form form %}


<input type="submit" class="btn btn-primary" value="Save" />
</form>




</div>
</div>

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

{%endblock%}
{%block extrajs%}
<script>
$(function(){

$("#id_target_date").datepicker();});
</script>
{%endblock%}

{%block date%}
{%endblock%}

issues/templates/issues/issue_pm.html
{%extends 'main/index.html'%}
{% load bootstrap3 %}
{% load staticfiles %}
{% load comments i18n %}

{% load threadedcomments_tags %}

{%block content%}
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="/complaints/">Issues</a></li>
            <li class="active">PM</li>
          </ol>

 <br>
          <h1>
<i class="fa fa-user"></i>
   Issue: <span class="">#{{complaint.id}} </span>
          </h1>

<br>
<p class="bg-orange"> <b>Created on:</b> {{complaint.created}}</p>
       <!-- Main content -->
        <section class="content">
        <div class="row">
<div class="col-md-12 "> 
         
{% if messages %}
<div class="alert alert-success" role="alert">
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</div>
{% endif %}

<h3><i class="fa fa-user"></i> Please select the PM related to this issue:

</h3>
<hr>

<div  class="panel panel-info">
    <div class="panel-body no-padding">
         <form enctype="multipart/form-data" action="" method="post" role="form" class="col-md-4">
{% csrf_token %}

              {% bootstrap_form form %}


<input type="submit" class="btn btn-primary" value="Open Issue" />
</form>


 

    </div><!-- /.box-body -->
  </div>




      <table class="table table-striped bring-up nth-2-center" id="layout-skins-list">
<tr>
<td><b>Status</b></td>
<td><span class="{%if complaint.status.title == "close" or complaint.status.title == "completed"%}label label-success {%else%} label label-danger {%endif%}">{{complaint.status}}</span> 
{%if complaint.status.title == "completed" %}
<a href="/complaints/resolve/{{complaint.id}}/" class="btn pull-right btn-danger">REOPEN</a>
{%else%}
<a href="/complaints/resolve/{{complaint.id}}/" class="btn pull-right btn-danger">CLOSE NOW</a>
{%endif%}
</td>
</tr>


<tr>
<td><b>Complaint No.</b></td>
<td>{{complaint.id}}</td>
</tr>
<tr>
<td><b>Site</b></td>
<td>{{complaint.site}}</td>
</tr>
<tr>
<td><b>Description</b></td>
<td>{{complaint.description}}</td>
</tr>
<tr>
<td><b>Date of Issue Filed</b></td>
<td>{{complaint.date_of_complaint}}</td>
</tr>
<tr>
<td><b>Outage Start Time</b></td>
<td>{{complaint.outage_start}}</td>
</tr>

{%if complaint.outage_end%}
<tr>
<td><b>Outage End Time</b></td>
<td>{{complaint.outage_end}}</td>
</tr>
<tr>
<td><b>Gen Loss (KWh)</b></td>
<td>{{complaint.genloss}}</td>
</tr>


{%endif%}

</table>


</div>
</div>

<div class="modal fade" id="dashboard-data" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title box-title" style="color:#000" id="myModalLabel">Details</h4>
      </div>
      <div class="modal-body">
Nothing here!

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>


        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

{%endblock%}
{%block scripts%}
<script>
$(function(){
$("#id_comment").attr("rows",5);
$("#id_comment").attr("cols",150);
$("#id_honeypot").hide();
$("#id_target_date").datepicker();

});
</script>
{%endblock%}

{%block date%}
{%endblock%}

issues/templates/issues/issues.html
  
{%extends 'main/index.html'%}
{% load bootstrap3 %}
{% load staticfiles %}
{%block sidemenu%}
{%include 'partials/issuetracker-menu.html'%}
{%endblock%}

{%block content%}    
           

 
                   <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

            <li class="active">Issues</li>
          </ol>

        <section class="content">
  

<br>
<div class="panel panel-default">
                <div class="panel-heading with-border accent-color">
                  <h3 class="box-title">Search Issues</h3>
</div>	
<div class="panel-body">
{% if messages %}
<div class="alert alert-info" role="alert">
    {% for message in messages %}
   {{ message }}
    {% endfor %}
</ul>
</div>
{% endif %}




               <form action="" method="post" class="mailbox-controls form form-inline" role="form">{%csrf_token%}
    {% bootstrap_form form %}
<br>
<br>
                    <button class="btn btn-primary next-first btn-raised">Search</button>

                </form>
</div>
</div>
<div class="panel panel-default">
<div class="panel-body">
{%include 'issues/alerts_tabs.html'%} 
</div>
</div>
</div>

           </section> 
{%endblock%}
{%block scripts%}
<script>
$(function(){
$("select").select2();
});
</script>
{%endblock%}
{%block extracss%}
<style type="text/css">
.help-block{
display:none;
}

.form-group{
width:auto !important;
}
.form-inline .control-label{
padding:16px;
}

</style>

{%endblock%}

issues/templates/issues/plantwise.html
{%extends 'main/index.html'%}
{%load bootstrap3%}
{%load staticfiles%}
{%block title%} Analysis | AkshyaPower {%endblock%}



{%block content%}

          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Issue Reports</li>
          </ol>
        <section class="content">
         
         
          <div class="row hidden-print">
            <div class="col-md-12">
              <div class="panel panel-default ">
                <div class="panel-heading ">
                    <h3 class="box-title">Reports</h3>

                </div><!-- /.box-header -->
                <div class="panel-body">
                  
<br>
{% if messages %}
          <div class="row">
            <div class="col-xs-12 table-responsive">
<div class="alert alert-success" role="alert">
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</div>

            

</div><!-- /.col -->
</div><!-- /.row -->

{% endif %}
<div class="row">
<div class="col-md-12 small">
  <form class="form form-inline" action="" method="post">{%csrf_token%}

              {% bootstrap_form form %}
<input type="hidden" name="parameter" value="breakdown"/>

<br>
<div class="form-group">

              <button type="submit" class="btn btn-raised btn-primary form-button">Go</button>
</div>
        </form>       
</div>
</div>
</div>
</div>
</div>
</div>


       <div class="row ajax-content">

{%include 'issues/analysis-rest.html'%}

</div>


        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->




{%endblock%}

{%block scripts%}
{%include "issues/plantwise.html.js"%}
{%endblock%}

{%block extracss%}
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:bold;padding:25px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-s6z2{text-align:center}
.tg .tg-cell{
font-weight:bold;
}
.help-block{
display:none;
}

.form-group{
width:auto !important;
}
.form-inline .control-label{
padding:16px;
}

</style>

{%endblock%}

issues/templates/issues/target_date.html
{% load bootstrap3 %}
{% load staticfiles %}


        <form enctype="multipart/form-data" action="/complaints/issue/{{issue.id}}/set_target_date/" method="post" role="form" class="col-md-12">
{% csrf_token %}

              {% bootstrap_form form %}


<input type="submit" class="btn btn-primary" value="Assign" />
</form>


<script>
$(function(){
$("#id_target_date").datepicker();
});
</script>