main/urls.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed 
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes  
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, 
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE 
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.                
'''



from django.conf.urls import url
from .views import *
urlpatterns = [
 
    url(r'^$', dashboard, name='dashboard'),
    url(r'^client/dashboard', client_dashboard, name='client_dashboard'),
    url(r'^inbox/$', issue_tracker, name='issue_tracker'),
    url(r'^manager/dashboard', manager_dashboard, name='manager_dashboard'),
    url(r'^user/(?P<id>\d+)/$', user_profile, name='user_profile'),
    #url(r'^client/inbox', client_inbox, name='client_inbox'),
] 

omportal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^pm/', include('prevmain.urls')),
    url(r'^site/', include('energysite.urls')),
    url(r'^complaints/', include('issues.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^issues/comments/', include('django_comments.urls')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prevmain/urls.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed 
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes  
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, 
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE 
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.                
'''




from django.conf.urls import url
from .views import *
urlpatterns = [
 
 
    url(r'^alerts/$', site_pm_alerts, name='pmalerts'),
    url(r'^schedules/$', pmschedules, name='pmschedules'),
    

    url(r'^update_pm/(?P<pm_id>\d+)/$', update_pm, name='update_pm'),
    url(r'^alert/(?P<pm_id>\d+)/$', view_pmalert, name='view_pmalert'),
    url(r'^pm_checklist/(?P<pm_alert>\d+)/$', pm_checklists, name='pm_checklist'),

    url(r'create/$', create_pm_schedule, name='create_pm'),
    url(r'^full_schedule/$', full_schedule, name='full-schedule'),
    url(r'^reports/$', reports, name='reports'),

    url(r'^checklist/(?P<pm_alert>\d+)/$',pm_save_checklist, name='checklist_pmalert'),

    url(r'^pmr/$', pmr, name='pmr'),
    url(r'^summary/$', pm_summary, name='pm_summary'),
    url(r'^checklists/$', checklists, name='checklists'),
] 

prevmain/models.py
'''
 GEEKYBUDDHA TECHNOLOGIES PVT. LTD. CONFIDENTIAL
 Unpublished Copyright (c) 2015-2016 GEEKYBUDDHA TECHNOLOGIES PVT. LTD., All Rights Reserved.

 NOTICE:  All information contained herein is, and remains the property of GEEKBUDDHA TECHNOLOGIES PVT. LTD.. The intellectual and technical concepts contained
 herein are proprietary to GEEKYBUDDHA TECHNOLOGIES PVT. LTD. and may be covered by INDIAN and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
 from GEEKYBUDDHA TECHNOLOGIES PVT. LTD..  Access to the source code contained herein is hereby forbidden to anyone except current GEEKYBUDDHA TECHNOLOGIES PVT. LTD. employees, managers or contractors who have executed
 Confidentiality and Non-disclosure agreements explicitly covering such access.

The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes
information that is confidential and/or proprietary, and is a trade secret, of  GEEKYBUDDHA TECHNOLOGIES PVT. LTD..   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OFAPPLICABLE
LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
'''




from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from smart_selects.db_fields import ChainedForeignKey

class Company(models.Model):
	name = models.CharField(max_length=50,help_text="Your company's registered name for the records")
	website = models.URLField(max_length=255,help_text="Please include http in the url ")
	contact_email = models.EmailField(max_length=255, help_text="Enter a valid email address of contact person")
	contact_number = models.CharField(help_text="Enter Mobile Number of contact person",max_length=10)
	city = models.CharField(max_length=255, help_text="Enter city where head office is located")
	country = models.CharField(max_length=255,help_text="Enter the country name")
	address = models.TextField(help_text="Enter full address for the records")
	logo = models.ImageField(upload_to="logos")
	def __unicode__(self):
                return '%s' % (self.name)



class EnergySite(models.Model):
	name = models.CharField(max_length=255,help_text="Please enter name for the site")
	city = models.CharField(max_length=255,help_text="Please enter city/town name for the site")
        location = models.CharField(max_length=100,help_text="Please click on the location in the map to get co-ordiantes")
	capacity = models.FloatField(help_text="Please enter site DC capacity in MW")
	ac_capacity = models.FloatField(help_text="Please enter site AC capacity in MW")
	tvm_mf = models.FloatField(help_text="Please enter multiplication factor to be used in DGR calculuation")
	no_of_blocks = models.IntegerField(help_text="Please enter no. of blocks")
	ppa = models.FloatField(help_text="Enter PPA price in Rs. per unit",verbose_name="Tariff")
	address = models.TextField(help_text="Please enter full site address for the communication")
	STATES = (
		('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
		('Andhra Pradesh' ,'Andhra Pradesh'),
		('Arunachal Pradesh','Arunachal Pradesh'),
		('Assam','Assam'),
		('Bihar	','	Bihar'),
		('Chandigarh','Chandigarh'),
		('Chhattisgarh','	Chhattisgarh'),
		('Dadra and Nagar Haveli','	Dadra and Nagar Haveli'),
		('Daman and Diu','	Daman and Diu'),
		('Delhi','	Delhi'),
		('Goa','Goa'),
		('Gujarat','Gujarat'),
		('Haryana','Haryana'),
		('Himachal Pradesh','	Himachal Pradesh'),
		('Jammu and Kashmir','	Jammu and Kashmir'),
		('Jharkhand','Jharkhand'),
		('Karnataka','Karnataka '),
		('Kerala','Kerala'),
		('Lakshadweep','Lakshadweep'),
		('Madhya Pradesh','	Madhya Pradesh'),
		('Maharashtra','Maharashtra'),
		('Manipur','	Manipur'),
		('Meghalaya','	Meghalaya'),
		('Mizoram','	Mizoram'),
		('Nagaland','	Nagaland'),
		('Orissa','	Orissa'),
		('Pondicherry','	Pondicherry'),
		('Punjab','	Punjab'),
		('Rajasthan','	Rajasthan'),
		('Sikkim','	Sikkim'),
		('Tamil Nadu','	Tamil Nadu'),
		('Tripura','	Tripura'),
		('Uttaranchal','	Uttaranchal'),
		('Uttar Pradesh','	Uttar Pradesh'),
		('West Bengal','	West Bengal'),
	)
	state = models.CharField(choices=STATES,max_length=100)
	company = models.ForeignKey(Company)
	is_grouped = models.BooleanField(default=False)
	cubicles_per_inverter = models.IntegerField(default=1)
	datalogger_site_name = models.CharField(max_length=100)
        monitoring_url = models.URLField(default="https://scada.akshyapower.com")
        site_picture = models.ImageField(upload_to="site_pictures")
      	zone = models.CharField(default="none",max_length=100)
	def __unicode__(self):
                return '%s' % (self.city)

class Block(models.Model):
	site = models.ForeignKey(EnergySite)
	company = models.ForeignKey(Company)
	block = models.CharField(max_length=255)
	def __unicode__(self):
                return "%s" % self.block

class BlockExtras(models.Model):
	block = models.OneToOneField(Block)
	ac_capacity = models.FloatField()
	dc_capacity = models.FloatField()



class UserSite(models.Model):
	user = models.ForeignKey(User)
	site = models.ForeignKey(EnergySite,help_text="Choose the site you want to assign to this user")
	ROLES = (('manager','Manager'),
		 ('incharge','Incharge'),
		 ('client','Client'),
		)
	role = models.CharField(choices=ROLES,max_length=50,help_text="Choose the role of the user")


class UserCompany(models.Model):
	user = models.OneToOneField(User)
	company = models.ForeignKey(Company)
	is_viewer = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)
	is_stock_admin = models.BooleanField(default=False)
	is_client = models.BooleanField(default=False)
        ROLES = (('manager','Manager'),
		 ('incharge','Incharge'),
		 ('zonal_head','zonal_head'),
		 ('client','Client'),
		)
	role = models.CharField(choices=ROLES,max_length=50,help_text="Choose the role of the user")
        zone = models.CharField(max_length=100,null=True,blank=True)





class SiteNotification(models.Model):
	site = models.ForeignKey(EnergySite)
	notification = models.CharField(max_length=255)
	details = models.TextField(blank=True)
	action_url = models.CharField(max_length=255,blank=True)
	is_read = models.BooleanField(default=False)
	created = models.DateTimeField()
	user = models.ForeignKey(User)
	category = models.CharField(max_length=255,blank=True,null=True)
	def __unicode__(self):
                return 'site_alert'



class Location(models.Model):
	name = models.CharField(max_length=40)
	def __unicode__(self):
                return '%s' % (self.name)

class EquipmentCatagory(models.Model):
        name = models.CharField(max_length = 100)
        def __unicode__(self):
                return '%s' % (self.name)

class Equipment(models.Model):
	name = models.CharField(max_length=40)
	location = models.ForeignKey(Location)
	site = models.ForeignKey(EnergySite,blank=True,null=True)
	equipment_catagory = models.ForeignKey(EquipmentCatagory, blank = True, null = True)
	def __unicode__(self):
                return '%s' % (self.name)

	


class Section(models.Model):
	location =models.ForeignKey(Location)
	name = models.CharField(max_length=40)
	def __unicode__(self):
                return '%s' % (self.name)

class EquipmentSection(models.Model):
	equipment =models.ForeignKey(Equipment)
	name = models.CharField(max_length=40)
	def __unicode__(self):
                return '%s' % (self.name)



class Years(models.Model):
	YEAR = (('2013','2013'),
		 ('2014','2014'),
		 ('2015','2015'),
		 ('2016','2016'),
		 ('2017','2017'),
		 ('2018','2018'),
		 ('2019','2019'),
		 ('2020','2020'),
		 ('2021','2021'),
		 ('2022','2022'),
		 ('2023','2023'),
		 ('2024','2024'),
		 ('2025','2025'),
		)

	start = models.CharField(choices=YEAR,max_length=50)
	end = models.CharField(choices=YEAR,max_length=50)
	def __unicode__(self):
                return '%s - %s' % (self.start,self.end)


class PMSchedule(models.Model):
	financial_year = models.ForeignKey(Years)
	site = models.ForeignKey(EnergySite)
        block = models.ForeignKey(Block,
	blank=True,
	null=True
        )


	#location = models.ForeignKey(Location)
        equipment = models.ManyToManyField(
        Equipment,
        )
	section = ChainedForeignKey(
        Section,
        chained_field="location",
        chained_model_field="location",
        show_all=False,
        auto_choose=True,
	blank=True,
	null=True
        )


	equipment_section = ChainedForeignKey(
        EquipmentSection,
        chained_field="equipment",
        chained_model_field="equipment",
        show_all=False,
        auto_choose=True,
	blank=True,
	null=True
        )


	details = models.CharField(max_length=100)
	FREQ = (
		('daily','daily'),
		('weekly','weekly'),
		('fortnightly','Fortnightly'),
		 ('monthly','Monthly'),
		 ('quarterly','Quarterly'),
		 ('halfyearly','Halfyearly'),
		 ('yearly','Yearly'),
		 ('one_time','one_time'),
		)
	frequency = models.CharField(choices=FREQ,max_length=50)
	pm_type = models.CharField(choices=FREQ,max_length=50, blank = True, null = True)
	DATES = (('1','1'),
		 ('2','2'),
		 ('3','3'),
		 ('4','4'),
		 ('5','5'),
		 ('6','6'),
		 ('7','7'),
		 ('8','8'),
		 ('9','9'),
		 ('10','10'),
		 ('11','11'),
		 ('12','12'),
		 ('13','13'),
		 ('14','14'),
		 ('15','15'),
		 ('16','16'),
		 ('17','17'),
		 ('18','18'),
		 ('19','19'),
		 ('20','20'),
		 ('21','21'),
		 ('22','22'),
		 ('23','23'),
		 ('24','24'),
		 ('25','25'),

prevmain/templates/prevmain/checklist.html
  
{%extends 'main/index.html'%}
{% load bootstrap3 %}
{%block content%}    
         <div class="col-md-12"> 
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">PM Report</li>
          </ol>
</div>
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->

{% if messages %}
<div class="alert alert-success" role="alert">
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</div>
{% endif %}

 
              <div class="panel panel-default ">
                <div class="panel-heading">
 <h1>
           Please update check list items -  
            <small>{{site}} </small>
          </h1>        
       </div><!-- /.box-header -->
                <!-- form start -->
<div class="panel-body"> 



<table class="table table-bordered">
<tr>
<td>Equipment</td>
<td>{{pm.equipment}}</td>
</tr>
<tr>
<td>Details</td>
<td>{{pm.pmschedule.details}}</td>
</tr>
<tr>
<td>Block </td>
<td>{{pm.block}}</td>
</tr>


<tr>
<td>Due Date</td>
<td>{{pm.due_date}}</td>
</tr>



</table> 

              <form action="" class="form form-inline" method="post" role="form" enctype="multipart/form-data">{%csrf_token%}
{{ formset.management_form }}
{%for form in formset%}
{% if form.errors %}
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">×</button>
		{% for field in form %} 
			{% if field.errors %}
			<li>{{ field.label }}: {{ field.errors|striptags }}</li>
			{% endif %}
		{% endfor %}
	</div>
{% endif %}

{%bootstrap_form form%}
<br>
{%endfor%}
<div class="form-group">
<button class="btn btn-danger" type="submit">Submit</button>
</div>
                </form>
</div>
              </div><!-- /.box -->






          </div>   <!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

             {%endblock%} 

{%block scripts%}
<script>
$(function(){
$("#id_new_date").datetimepicker();
});
</script> 
{%endblock%}



{%block extracss%}
<style>
select{
max-width:200px;
}

.form-group{
width:250px;
max-width:250px;
}
.help-block{
display:none;
}
</style>
{%endblock%}

prevmain/templates/prevmain/checklists.html
{%extends 'main/index.html'%}
{%load bootstrap3%}
{%load staticfiles%}

{%block content%}


          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Reports</li>
          </ol>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <h3 class="box-title">Equipment Wise Checklists</h3>
               </div><!-- /.box-header -->
                <div class="panel-body">

      

<div class="search-results col-md-12">
<table class="table table-bordered">
<tr><th>Equipment
</th>
<th>Checklist
</th>
<th>PM Type
</th>
<th>Desired Value
</th>


</tr>


{%for item in checklists%}
<tr>
<td>{{item.equipment_catagory}}</td>
<td>{{item}}</td>
<td>{{item.pm_type}}</td>
<td>{{item.correct_value}}</td>

</tr>

{%endfor%}
</table>
</div>


          </div>
                </div>
              </div><!-- /. box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->


{%endblock%}

{%block scripts%}

<script src="{%static "reports.js"%}"></script>

{%endblock%}

prevmain/templates/prevmain/full_schedule.html
  
{%extends 'main/index.html'%}
{% load bootstrap3 %}
{% load staticfiles %}



{%block content%}    
           

 
        <section class="content-header">
  
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

            <li >PM</li>
            <li class="active">Full Schedule</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
<div class="panel">

<div class="panel-body">
{% if messages %}
<div class="alert alert-info" role="alert">
    {% for message in messages %}
   {{ message }}
    {% endfor %}
</ul>
</div>
{% endif %}




               <form action="" method="post" class="mailbox-controls form form-inline" role="form">{%csrf_token%}
    {% bootstrap_form form %}
                    <button class="btn btn-raised btn-primary next-first">View</button>
                    

                </form>
</div>
</div>
<div class="panel">
<div class="panel-body">
<table class="table table-bordered table-stripped bg-gray">
{%for data in reports%}
<tr>
<td class="bg-red">
{{data.equipment}}
</td>
</tr>
<tr>
{%for alert in data.alerts%}
<td>
</td>

<td>
    <h3>{% ifchanged alert.due_date %} {{ alert.due_date }} {% endifchanged %}</h3>
<br>
{{alert.pmschedule.details}} {%if alert.section%}{{alert.section}}{%else%} {{alert.block}}{%endif%}
</td>
</tr>
{%endfor%}

{%endfor%}
 </table>


</div>
</div>



           </section> 
</div>
{%endblock%}

{%block reports%}

{%endblock%}


{%block extracss%}
<style type="text/css">
.help-block{
display:none;
}

.form-group{
width:auto !important;
}
.form-inline .control-label{
padding:16px;
}

</style>

{%endblock%}

prevmain/templates/prevmain/pmr.html
  
{%extends 'main/index.html'%}
{% load bootstrap3 %}
{%block content%}    

<form action="" method="post">{%csrf_token%}

    {% bootstrap_form form %}

                    <button class="btn btn-primary btn-raised next-first">SAVE</button>

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                  </div>
                </form>
              </div><!-- /.box -->






          </div>   <!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

             {%endblock%} 

{%block scripts%}
<script>
$(function(){
$("#id_new_date").datetimepicker();
});
</script> 
{%endblock%}

prevmain/templates/prevmain/pmschedules.html
{%extends 'main/index.html'%}

{%load bootstrap3%}

{%block content%}
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">PM</li>
          </ol>
        <section class="content">
          <div class="row">

{% if messages %}
<div class="alert alert-success" role="alert">
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</div>
{% endif %}

 


<div class="col-md-12 "> 
<div class="panel panel-primary">
<div class="panel-body">
  <form class="report-form form " action="" method="post" role="form">{%csrf_token%}
              {% bootstrap_form form %}

              <button type="submit" class="btn-raised form-button btn btn-primary">Filter</button>
              <a href="/pmschedules/" class="btn-raised btn btn-link">Reset</a>
        </form>        
</div>
</div>
</div>

<div class="panel panel-primary">
<div class="panel-body">
 
<div class="ajax-content col-md-12">
<div id="calendar"></div>
</div>
</div>
</div>
{%endblock%}


{%block scripts%}
<script>

$(function(){

/* initialize the calendar
         -----------------------------------------------------------------*/
        $('#calendar').fullCalendar({
          header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
          },
          buttonText: {
            today: 'today',
            month: 'month',
            week: 'week',
            day: 'day'
          },
          //Random default events
          events: [
        {%for event in events%}  
	  {
              title: '{{event.site}} - {%if event.pmschedule.block%} {{event.pmschedule.block}} {%endif%}{{event.equipment}} - {{event.pmschedule.details}}',
              start: new Date({{event.due_date.year}},{{event.due_date.month}}-1, {{event.due_date.day}}),

              url: '/pm/alert/{{event.id}}/',
	{%if event.status == "completed"%}

	      backgroundColor: "#00a65a", //Success (green)
              borderColor: "#00a65a", //Success (green)
	{%else%}
              backgroundColor: "#f56954", //red
              borderColor: "#f56954", //red
	{%endif%}
 
            },
	{%endfor%}
          ],
                  });

      });
</script>

<script>
$(function(){
$('form').ajaxForm({ 
        // target identifies the element(s) to update with the server response 
        target: '.ajax-content', 
	beforeSubmit: showRequest, 
        // success identifies the function to invoke when the server response 
        // has been received; here we apply a fade-in effect to the new content 
        success: function() { 
            $('.ajax-content').fadeIn('slow'); 
	    $(".form-button").text("Filter");
	    $.notify("Filtered", "success"); 
        } 
    }); 



});

// pre-submit callback 
function showRequest(formData, jqForm, options) { 
	$(".form-button").text("Loading..");
    return true; 
} 

</script>
{%endblock%}

prevmain/templates/prevmain/site_pm_alerts.html
  
{%extends 'main/index.html'%}
{% load bootstrap3 %}
{% load staticfiles %}


{%block content%}    
           

 
        <section class="content-header">
  
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

            <li class="active">PM</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
<div class="panel panel-primary">
<div class="panel-body">
{% if messages %}
<div class="alert alert-info" role="alert">
    {% for message in messages %}
   {{ message }}
    {% endfor %}
</ul>
</div>
{% endif %}




               <form action="" method="post" class="mailbox-controls form form-inline" role="form">{%csrf_token%}
    {% bootstrap_form form %}
                    <button class="btn btn-raised btn-primary next-first">Search</button>

                </form>
</div>
</div>
<div class="panel panel-primary">
<div class="panel-heading">
<h1>Preventive Maintenance Tickets</h1>
</div>
<div class="panel-body">
{%include 'prevmain/alerts_tabs.html'%} 

</div>
</div>
           </section> 
{%endblock%}

{%block scripts%}
<script>
$(function(){
$("#id_equipment").select2();
});
</script>
{%endblock%}


{%block extracss%}
<style>
#id_equipment{
width:200px;
}

.select2-container{
width:200px;

}
</style>
{%endblock%}